title: Beyond the Brief
description: Personal blog by Shiva K. (SRMK) — Cyber Security, Business Analysis, Project Management, and Training & Assessment.
theme: minima
author: "Shiva K. (SRMK)"
timezone: Australia/Melbourne
